name: Build Gradle project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Create local.properties file
        run: |
          touch local.properties
          echo "add things you want here"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run tests with Gradle Wrapper
        run: ./gradlew check